Model  = architecture + parameters

### 1 引入

In [3]:
import torch as t

t.cuda.is_available(), t.cuda.device_count()

(True, 1)

### 2 数据定义与运算
默认是float64?，可以用dtype=long64等修改

In [94]:
a = t.Tensor([1])
dir(a) #Tensor的属性

['__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem_

In [85]:
x = t.ones(4)
y = t.Tensor([1,2,3,4])
z = t.rand(3,4)
print(z.size())
x, y, x+y, z

torch.Size([3, 4])


(tensor([1., 1., 1., 1.]),
 tensor([1., 2., 3., 4.]),
 tensor([2., 3., 4., 5.]),
 tensor([[0.1981, 0.5622, 0.9700, 0.9177],
         [0.9917, 0.6666, 0.1691, 0.4438],
         [0.9295, 0.8348, 0.3967, 0.9419]]))

In [86]:
display(z.transpose(1,0))#表示1和0的轴互换
z

tensor([[0.1981, 0.9917, 0.9295],
        [0.5622, 0.6666, 0.8348],
        [0.9700, 0.1691, 0.3967],
        [0.9177, 0.4438, 0.9419]])

tensor([[0.1981, 0.5622, 0.9700, 0.9177],
        [0.9917, 0.6666, 0.1691, 0.4438],
        [0.9295, 0.8348, 0.3967, 0.9419]])

In [87]:
t.rand(1,2,3,4).transpose(0,1).transpose(2,3).shape

torch.Size([2, 1, 4, 3])

In [88]:
y.add_(x)#inplace操作

tensor([2., 3., 4., 5.])

#### sum/max等运算

In [89]:
z

tensor([[0.1981, 0.5622, 0.9700, 0.9177],
        [0.9917, 0.6666, 0.1691, 0.4438],
        [0.9295, 0.8348, 0.3967, 0.9419]])

In [91]:
z.sum() #全部加起来

tensor(8.0220)

In [92]:
print(z.sum(0)) #沿着第二维的方向进行sum
print(z.sum(1)) #沿着第二维的方向进行sum

tensor([2.1193, 2.0636, 1.5358, 2.3034])
tensor([2.6480, 2.2711, 3.1029])


In [93]:
z1, z2 = z.max(0)#加上数字就是：分别取
print(z1) #max对应的value
print(z2) #max对应的index

tensor([0.9917, 0.8348, 0.9700, 0.9419])
tensor([1, 2, 0, 2])


#### item 把tensor变成scaler

In [111]:
x = t.zeros(1)
x, x.item()#把单元素tensor变成scaler

(tensor([0.]), 0.0)

#### 取某维元素

In [121]:
z[:,0]#和numpy用法一样，取第二个维度的第一溜！！第二个维度就是行标，对应这里就是第一列

tensor([0.4318, 0.6425, 0.1328])

#### view操作

In [122]:
z.view(1,-1) #reshape操作，没有inplace

tensor([[0.4318, 0.0681, 0.8016, 0.3535, 0.6425, 0.5646, 0.3702, 0.3102, 0.1328,
         0.2300, 0.9559, 0.6918]])

#### numpy bridge以及变量赋值问题（python赋值相当于 引用）

In [60]:
import numpy as np
a = np.zeros(1)
b = t.from_numpy(a)
b

tensor([0.], dtype=torch.float64)

In [130]:
a = t.zeros(1)
b = a.numpy()# numpy bridge
a, b

(tensor([0.]), array([0.], dtype=float32))

#### 插播非常重要的python赋值与传参问题
传参都是引用  
等号赋值会创建新对象
* 不可变变量的修改会创建新对象
* 可变对象修改就在原始地址上改

In [161]:
a = 1
b = a
b = 2
print(a, b)

1 2


In [163]:
a = [1]
b = a
b += [2]
print(a, b)

[1, 2] [1, 2]


In [158]:
a = [1]
print(id(a),a)
a += [2]
print(id(a),a)

2473518379464 [1]
2473518379464 [1, 2]


In [157]:
a = 1
print(id(a),a)
a += 1
print(id(a),a)

1745051808 1
1745051840 2


终结者case：

In [178]:
def func(m):
    m[0] = 10
    print(id(m))
    #传了地址
    m = [100,200,300]
    print(id(m))
    #为m重开了地址'
    return m

m = [1,2,3]
print('元素地址:',id(m))

func(m)
print('元素地址',id(m),m)
m=func(m)
print('返回新地址:',id(m),m)

元素地址: 2473647109768
2473647109768
2473647108360
元素地址 2473647109768 [10, 2, 3]
2473647109768
2473647108360
返回新地址: 2473647108360 [100, 200, 300]


#### 3 CUDA使用
在cpu/gpu间切换运算

In [184]:
if t.cuda.is_available():
    device = t.device('cuda')
    y = t.ones_like(x, device=device)#生成：和x形状一样的y
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to('cpu',t.double))#可以在这顺便转换类型

tensor([2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2.], dtype=torch.float64)


In [61]:
y.to("cpu").data.numpy()#一个Tensor不能直接取data，要转到cpu上才行

#或者写
y.cpu().data.numpy()

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
# 一般是把整个模型变成cuda，即在GPU
model = model.cuda()

#### 4 自动求导autograd

In [33]:
x = t.arange(4, requires_grad=True, dtype=t.float).view(2,2)
y = 2*x
print(x)
print(y)
print(y.grad_fn)
y.type(t.LongTensor)#.float() #这样是没有grad的

tensor([[0., 1.],
        [2., 3.]], grad_fn=<ViewBackward>)
tensor([[0., 2.],
        [4., 6.]], grad_fn=<MulBackward0>)


tensor([[0, 2],
        [4, 6]])

In [39]:
print(x.sum(0)) #沿着第一维来sum
print(x.sum(1))
z=y.sum()
z

tensor([2., 4.], grad_fn=<SumBackward2>)
tensor([1., 5.], grad_fn=<SumBackward2>)


tensor(12., grad_fn=<SumBackward0>)

In [35]:
z.backward()#只有scaler才能backward()，刚开始grad=1

In [36]:
print(x.grad, y.grad, sep='\n')

None
None


In [96]:
print((x**2).requires_grad)
with t.no_grad():
    print((x**2).requires_grad)


True
False


In [41]:
from fastai.vision import Learner